### PR TITLE
update term 2/2024 team structure

### LINKED ISSUE #3: Update website content
**Is your feature request related to a problem? Please describe.**
Before the website gets launched, the data needs to be updated, including:

- Stats
- Past project reports
- Study resources
- Term 2/24 team structure

**Describe the solution you'd like**
Hope we can get this done before the development finishes. Also, ask CR how to get the site launched onto the domain, i.e. tutors-in-action.org.

Last but not least, check and report typos or bugs.

**Describe alternatives you've considered**
N/A

**Additional context**
May ask other TIA comittee members to write the reports in markdown.

### PR DESCRIPTION
**Pull request by raihanahhusna**
Update team structure term 2/2024.

Fixes #3 

## Type of change

- Content update

*Please delete options that are not relevant.*

## Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have tested the website locally with my changes, and I am sure that it works well on different screen sizes

### CODE REVIEW

**Comment by jaredliw** [comment]
lgtm! thanks for the great work!

But there is a thing:
image
The structure is incorrect, as u can see the open and close tags cross.

And code format runs a bit, make sure it is consistant. Configure your IDE well so that it can do this for you.

Ask one mate to review and merge this PR pls. Make sure to double check the names and positions are correct.

**Comment by jaredliw** [comment]
A small tip on how to review the code:

```bash
gh pr checkout 7
```
(need to install Github CLI)

and you will be able to view this PR commits locally on a new branch.

**Comment by AARandom** [comment]
bloop

Hey Jared, the inconsistent div tags are supposed to create a new row to separate the director and executives. 

The div tags between the if and end blocks will be placed dynamically.

So like, <div original>  ...range...  </div from if> <div from if>  ...continue range...  </div original> (can refer pic)

But we'll work on the formatting tho, forgot about it there. Thanks for pointing it out!

**Review by jaredliw — COMMENTED** [review]
I think it is all good now, feel free to merge this PR!

**Review by jaredliw — COMMENTED** [review]
I think it is all good now, feel free to merge this PR!

**Review by jaredliw — APPROVED** [review]

**Comment by jaredliw** [comment]
@raihanahhusna @AARandom 

Merge urselves once ok ya

**Comment by AARandom** [comment]
Thanks jared!

**Pull request merged**
