### PR TITLE
Add New Complaint form

### LINKED ISSUE #17: add section for complaint form

### PR DESCRIPTION
**Pull request by stingynoodles**
Fixes #17 (issue)

## Type of change

- Enhancement 

## Description of changes
- Created a complaint form below FAQs under the 'join us' page
- Linked the complaint form in the website to a new Google sheet for data tracking purposes 

## Feature
- Google sheet linked: https://docs.google.com/spreadsheets/d/1lVmxynvKp2DU2X5HQ4_Xu9hNUtE-1IjmDy0qU7VVeWY/edit?usp=drivesdk

## Updated:
- layouts/page/join-us.html

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have tested the website locally with my changes, and I am sure that it works well on different screen sizes

### CODE REVIEW

**Comment by jaredliw** [comment]
I have set the indent to 4 spaces, as it was hard to compare the changed lines in GitHub.
I'll leave the review to other members. I'll add on afterwards if there is anything necessary.

Btw, is the form reacheable for those who want to lodge a complaint? I dont expect it to be under 'Join Us' tho...
If I were to do, I will set a new page and put a new column under the footer:
image

**Comment by lynngoh7** [comment]
I agree with Jared, I think instead of placing the form under "Join Us" we can just add it below General Inquiries and Sponsorships so that it can be accessed easily.

**Comment by aidil-sekandar** [comment]
### New page for the complaint form
/tia/complaint-form (same link as the old site)

image
image

I am not really sure about the link, i just added another column in the footer (lmk if you wanna change the "having any issues?")

image

and sorry about this, i forgot to disable my formatter, so it automatically formatted the code to 2 spaces indent (only for the complaint-form.html file)
I have tested the form submition before commit, and everything is working as intended.

**Comment by jaredliw** [comment]
> ### New page for the complaint form
> /tia/complaint-form (same link as the old site)
> 
> image
> image
> 
> I am not really sure about the link, i just added another column in the footer (lmk if you wanna change the "having any issues?")
> 
> image
> 
> and sorry about this, i forgot to disable my formatter, so it automatically formatted the code to 2 spaces indent (only for the complaint-form.html file)
> I have tested the form submition before commit, and everything is working as intended.

Thanks aidil. ❤️
Im sorry, but lemme hint you smth 😜
Is the form properly validated? E.g. can one submit the form without choosing any "acting role"?

And one more:

By looking at these lines, I suspect (not tested, afk) if any input field contains '&' or '=', the data collected will go wrong. Cauz it is not differentiable whether the char is a part of the content, or a delimiter.

There are lots of twists and turns in the js. See if it is possible to be made more elegant.

**Comment by aidil-sekandar** [comment]
Thank you, Jared, for the review, and I apologize for the late response. Here’s my response to your concerns:
1.	Validation – If the user doesn't choose an acting role, they will not be able to submit the form.
2.	Encoding – I have added the 'pattern' attribute to the input elements with appropriate regex. If the user doesn't follow the correct format, they won't be able to submit the form.

-	Name input (full name, tutor/tutee names, subjects): pattern="[A-Za-z\s]+" — This will only allow alphabets (no numbers or symbols).
 
image

-	Number input (phone number) – pattern="\d{10,12}" — This allows only numbers within a 10 to 12 digit range (no dashes or other symbols). 

image

-	Text input (Details of the Complaint, date and medium used to file the complaint) – No pattern attribute for this, but there's an additional encoding step that retains symbols.
 
image

3.	Elegance – I’ve done my best to make the code more elegant. but this is the best I could do for now (im sorry, I haven’t worked with JavaScript in a while).

SAMPLE:
image
image

RESPONSE RESULT:
image

*you can check in the google sheet for full result
That's all for now

**Comment by jaredliw** [comment]
Thanks Aidil, lgtm. Im good with this.

Anything else from anyone?

**Comment by lynngoh7** [comment]
Nothing to add from me.

**Review by aidil-sekandar — APPROVED** [review]
- [x] Design and Layout
- [x] Functionality
- [x] Validation

**Pull request merged**
